I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/historia.rpy", line 398, in script
    show conde default at left
Exception: Image 'conde' does not accept attributes 'default'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/historia.rpy", line 398, in script
    show conde default at left
  File "C:\Users\Etec Paulino Botelho\Downloads\renpy-8.3.3-sdk\renpy\ast.py", line 1111, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\Etec Paulino Botelho\Downloads\renpy-8.3.3-sdk\renpy\ast.py", line 1074, in show_imspec
    renpy.config.show(name,
  File "C:\Users\Etec Paulino Botelho\Downloads\renpy-8.3.3-sdk\renpy\exports\displayexports.py", line 477, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\Etec Paulino Botelho\Downloads\renpy-8.3.3-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\Etec Paulino Botelho\Downloads\renpy-8.3.3-sdk\renpy\display\displayable.py", line 249, in _duplicate
    args.extraneous()
  File "C:\Users\Etec Paulino Botelho\Downloads\renpy-8.3.3-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'conde' does not accept attributes 'default'.

Windows-10-10.0.19041 AMD64
Ren'Py 8.3.3.24111502
 1.0
Fri Nov 22 20:33:32 2024
