I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 22, in script
    $ resposta, persistent.alunoID = checkLogin(username,senha,"tb_aluno","alunoLogin")
  File "game/script.rpy", line 22, in <module>
    $ resposta, persistent.alunoID = checkLogin(username,senha,"tb_aluno","alunoLogin")
  File "game/bd.rpy", line 78, in checkLogin
    return resposta,resultadoID
UnboundLocalError: local variable 'resultadoID' referenced before assignment

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 22, in script
    $ resposta, persistent.alunoID = checkLogin(username,senha,"tb_aluno","alunoLogin")
  File "C:\Users\Etec Paulino Botelho\Downloads\renpy-8.3.2-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Etec Paulino Botelho\Downloads\renpy-8.3.2-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 22, in <module>
    $ resposta, persistent.alunoID = checkLogin(username,senha,"tb_aluno","alunoLogin")
  File "game/bd.rpy", line 78, in checkLogin
    return resposta,resultadoID
UnboundLocalError: local variable 'resultadoID' referenced before assignment

Windows-10-10.0.19041 AMD64
Ren'Py 8.3.2.24090902
Trilhas do Brasil 1.0
Wed Oct  2 20:25:19 2024
