I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/bd.rpy", line 4, in script
    init python:
  File "game/bd.rpy", line 28, in <module>
    BD = checaConexao("trilhadobrasil")
  File "game/bd.rpy", line 20, in checaConexao
    mydb = conectabd(bancodedados)
  File "game/bd.rpy", line 9, in conectabd
    mydb = mysql.connector.connect(
InterfaceError: 2003: Can't connect to MySQL server on 'localhost:3306' (10061 Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/bd.rpy", line 4, in script
    init python:
  File "C:\Users\Etec Paulino Botelho\Downloads\renpy-8.3.2-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Etec Paulino Botelho\Downloads\renpy-8.3.2-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/bd.rpy", line 28, in <module>
    BD = checaConexao("trilhadobrasil")
  File "game/bd.rpy", line 20, in checaConexao
    mydb = conectabd(bancodedados)
  File "game/bd.rpy", line 9, in conectabd
    mydb = mysql.connector.connect(
  File "python-packages/mysql/connector/pooling.py", line 323, in connect
  File "python-packages/mysql/connector/connection.py", line 179, in __init__
  File "python-packages/mysql/connector/abstracts.py", line 1399, in connect
  File "python-packages/mysql/connector/connection.py", line 357, in _open_connection
  File "python-packages/mysql/connector/network.py", line 760, in open_connection
InterfaceError: 2003: Can't connect to MySQL server on 'localhost:3306' (10061 Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente)

Windows-10-10.0.19041 AMD64
Ren'Py 8.3.2.24090902
Trilhas do Brasil 1.0
Wed Nov  6 21:04:00 2024
